### DISCUSSION TITLE
Including multiple layers in a single file

### DISCUSSION THREAD

**Discussion by pnorman** [unvt/charites#114] [Q&A]
I have a style with related layers. When I ran the autoconvert, I ended up with one file per layer, like below.

<details>

```yaml
name: Spirit
version: 8
sources:
  spirit:
    type: vector
    url: http://127.0.0.1:8000/tilejson.json
layers:
  - !!inc/file style/background.yml
  - !!inc/file style/building-fill.yml
  - !!inc/file style/building-outline.yml
  - !!inc/file style/water.yml
  - !!inc/file style/water-lines.yml
  - !!inc/file style/roads-casing.yml
  - !!inc/file style/water-line-text.yml
glyphs: https://go-spatial.github.io/carto-assets/fonts/{fontstack}/{range}.pbf
```

</details>

I'd like to put both building-related layers in the same file, but can't figure out how to do so.

I tried making a yaml file with two array items, but this didn't work, because it will have made a yaml with an array of arrays. What I want is similar to the built-in yaml `<<: *anchor` syntax.
