### ISSUE TITLE
No error output when failing to build

### ISSUE THREAD

**Issue by pnorman** [unvt/charites#113]
**Describe the bug**
When failing to build a style, charites exits with return code 1 but doesn't report any errors

**To Reproduce**

1. Create an invalid style (see attached)
2. Build with `charites build`

**Expected behavior**
Output to stderr indicating what failed

**Charites Version:**

- Charites version: 0.1.4

**Desktop (please complete the following information):**

- OS: Linux

```yaml
name: Test
version: 8
sources:
  spirit:
    type: vector
    url: http://127.0.0.1:8000/tilejson.json
layers:
  - !!inc/file foo.yml
glyphs: https://go-spatial.github.io/carto-assets/fonts/{fontstack}/{range}.pbf
```

foo.yaml
```yaml
  - id: building-fill
    source: spirit
  - id: building-outline
    source: spirit
```
